version: '2'
services: 
  srs-postgresql:
    extends:
      file: sgtpm-postgresql.yaml
      service: sgtpm-postgresql
    container_name: sgtpm-postgresql

  rabbitmq:
    extends:
      file: rabbitmq.yaml
      service: rabbitmq
    container_name: rabbitmq

  elasticsearch:
    extends:
      file: elasticsearch.yaml
      service: elasticsearch
    container_name: elasticsearch
  